import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styling/globals.css";
import { Toaster } from "@/components/ui/toaster";
import React from "react";
import ThemeProvider from "@/components/darkMode/theme-provider";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={inter.className + " custom-scrollbar"}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Header />
            {children}
            <Toaster />
        </ThemeProvider>
        </body>
        </html>
    );
}